path:
  data: ./data/SS3_multireso_19channels.npz


  cheb:  ./Graph/P002_graphs/adj_DD_knn_k4.mat
  save: ./result/

train:
  channels: 19
  fold: 1
  context: 5
  epoch: 50
  batch_size: 64
  optimizer: adam
  learn_rate: 0.001
  lr_decay: 0.0

  project: spindle-graphsleepsnet_time_point

model:
  adj_matrix: "DD"
  Globaldense: "16"
  GLalpha: 0.0001
  cheb_filters: 10
  time_filters: 10
  time_conv_strides: 1
  time_conv_kernel: 3
  num_block: 1
  cheb_k: 3
  l1: 0
  l2: 0
  dropout: 0.5

sweep_wandb:

  id:  wbsv5p5j
              # 0kalyffs   #Learning rate sweep id_first


  method: bayes
  metric:
    name: fold0/val_best_f1_sweep
    goal: maximize
  parameters:
    learn_rate:
      distribution: log_uniform_values
      #min: 1e-5
      #max: 0.003
      min: 0.0015
      max: 0.006
